version: "3.7"

services:
  api:
    build:
      context: ./server
      dockerfile: ../docker/Dockerfile-server
    environment:
      DATABASE_URL: postgresql://todo:password@db/todo
      NODE_ENV: production
      SERVER_PORT: 3000
    depends_on:
      - db
    restart: unless-stopped
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; yarn --cwd /app start'

  webapp:
    build:
      context: ./web
      dockerfile: docker/Dockerfile-client
    restart: unless-stopped

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: todo
      POSTGRES_DB: todo
    ports:
      - 54321:5432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8001:80
    depends_on:
      - db
    restart: unless-stopped

  web:
    build:
      context: ./web
      dockerfile: ../docker/Dockerfile-web
    ports:
      - 8000:80
    depends_on:
      - api
      - webapp
      - pgadmin
    restart: unless-stopped
