FROM node:lts as build-env-client
WORKDIR /app

RUN mkdir client
COPY ./client/.yarnrc ./client/
COPY ./client/package.json ./client/
COPY ./client/yarn.lock ./client/
COPY ./client/tsconfig.json ./client
COPY ./client/public ./client/public
COPY ./client/src ./client/src

RUN mkdir -p server/src/graphql
COPY ./server/src/graphql/schema.graphql ./server/src/graphql

RUN mkdir -p tools
COPY ./tools/.yarnrc ./tools
COPY ./tools/codegen.yml ./tools
COPY ./tools/package.json ./tools
COPY ./tools/yarn.lock ./tools

RUN yarn --cwd tools install
RUN yarn --cwd tools build
RUN yarn --cwd client install
RUN yarn --cwd client build

FROM nginx
RUN mkdir -p /var/www/html
COPY --from=build-env-client /app/client/build /var/www/html
RUN chmod a+r /var/www/html/favicon.ico
RUN chmod a+r /var/www/html/*.png
